#!/usr/bin/env bash
# Bash script that manages:
# 	When passing the argument start:
# 		1. Starts manage_my_process
# 		2. Creates a file containing its PID in /var/run/my_process.pid
# 		3. Displays manage_my_process started
#	 When passing the argument stop:
# 		1. Stops manage_my_process
# 		2. Deletes the file /var/run/my_process.pid
# 		3. Displays manage_my_process stopped
# 	When passing the argument restart
# 		1. Stops manage_my_process
# 		2. Deletes the file /var/run/my_process.pid
# 		3. Starts manage_my_process
# 		4. Creates a file containing its PID in /var/run/my_process.pid
# 		4. Displays manage_my_process restarted
# 	Displays `Usage: manage_my_process {start|stop|restart}`
# 		if any other argument or no argument is passed

start() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	if [ "$1" -eq 1 ]; then echo "manage_my_process started"; fi
}

stop() {
	kill "$(pgrep -f './manage_my_process')"
	rm -f  /var/run/my_process.pid
	if [ "$1" -eq 1 ]; then echo "manage_my_process stopped"; fi
}

restart() {
	stop 0
	start 0
	echo "manage_my_process restarted"
}

case "$1" in
	start) start 1 ;;
	stop) stop 1 ;;
	restart) restart ;;
	*) echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
