#!/usr/bin/env bash
# Displays numbers from 1 to 100 and:
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5
#   Displays "Fizz" when the number is a multiple of 3
#   Displays "Buzz" when the number is a multiple of 5
#   Otherwise, displays the number

for nbr in {1..100}
do
	if (( nbr % 3 == 0 && nbr %5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( nbr % 3 == 0 ))
	then
		echo "Fizz"
	elif (( nbr % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$nbr"
	fi
done
