#!/usr/bin/env bash
# run server as nginx
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart